# Generated by Django 3.2.6 on 2022-04-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carditem',
            name='totals',
            field=models.FloatField(default=9),
            preserve_default=False,
        ),
    ]
