# Generated by Django 3.2.6 on 2022-05-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220421_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'accepted'), ('New', 'New'), ('Cenceled', 'Cenceled'), ('Completed', 'Completed')], default='New', max_length=10),
        ),
    ]
